// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppEigen.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// estimate_D
Rcpp::List estimate_D(const Eigen::VectorXd& r0, const Eigen::MatrixXd& masterZ, const Eigen::VectorXd& E, const Eigen::MatrixXd& masterV, const Eigen::MatrixXi& MAP, int n, int k, int t);
RcppExport SEXP _DCENt_estimate_D(SEXP r0SEXP, SEXP masterZSEXP, SEXP ESEXP, SEXP masterVSEXP, SEXP MAPSEXP, SEXP nSEXP, SEXP kSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type masterZ(masterZSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type E(ESEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type masterV(masterVSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type MAP(MAPSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_D(r0, masterZ, E, masterV, MAP, n, k, t));
    return rcpp_result_gen;
END_RCPP
}
// estimate_E
Rcpp::List estimate_E(const Eigen::VectorXd& r0, const Eigen::MatrixXd& masterZ, const Eigen::MatrixXd& D, const Eigen::MatrixXd& masterV, const Eigen::MatrixXi& MAP, int n, int k, int t);
RcppExport SEXP _DCENt_estimate_E(SEXP r0SEXP, SEXP masterZSEXP, SEXP DSEXP, SEXP masterVSEXP, SEXP MAPSEXP, SEXP nSEXP, SEXP kSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type r0(r0SEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type masterZ(masterZSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type masterV(masterVSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type MAP(MAPSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_E(r0, masterZ, D, masterV, MAP, n, k, t));
    return rcpp_result_gen;
END_RCPP
}
// estimate_all
Rcpp::List estimate_all(const Eigen::MatrixXd& X, const Eigen::VectorXd& y, const Eigen::MatrixXd& masterZ, const Eigen::MatrixXi& MAP, int n, int k, int t, int max_itr, double convergence_cutoff, bool REML, int n_fold, bool timings, bool verbose, int seed);
RcppExport SEXP _DCENt_estimate_all(SEXP XSEXP, SEXP ySEXP, SEXP masterZSEXP, SEXP MAPSEXP, SEXP nSEXP, SEXP kSEXP, SEXP tSEXP, SEXP max_itrSEXP, SEXP convergence_cutoffSEXP, SEXP REMLSEXP, SEXP n_foldSEXP, SEXP timingsSEXP, SEXP verboseSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type masterZ(masterZSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type MAP(MAPSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type max_itr(max_itrSEXP);
    Rcpp::traits::input_parameter< double >::type convergence_cutoff(convergence_cutoffSEXP);
    Rcpp::traits::input_parameter< bool >::type REML(REMLSEXP);
    Rcpp::traits::input_parameter< int >::type n_fold(n_foldSEXP);
    Rcpp::traits::input_parameter< bool >::type timings(timingsSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_all(X, y, masterZ, MAP, n, k, t, max_itr, convergence_cutoff, REML, n_fold, timings, verbose, seed));
    return rcpp_result_gen;
END_RCPP
}
// estimate_DEbeta
Rcpp::List estimate_DEbeta(const Eigen::Map<Eigen::MatrixXd> X, const Eigen::Map<Eigen::VectorXd> y, const Eigen::Map<Eigen::MatrixXd> masterZ, const Eigen::Map<Eigen::MatrixXi> MAP, int n, int k, int t, Eigen::ArrayXXd theta, int max_itr, double convergence_cutoff, bool REML, bool verbose, bool timings, int n_fold, bool custom_theta, int n_threads, int seed);
RcppExport SEXP _DCENt_estimate_DEbeta(SEXP XSEXP, SEXP ySEXP, SEXP masterZSEXP, SEXP MAPSEXP, SEXP nSEXP, SEXP kSEXP, SEXP tSEXP, SEXP thetaSEXP, SEXP max_itrSEXP, SEXP convergence_cutoffSEXP, SEXP REMLSEXP, SEXP verboseSEXP, SEXP timingsSEXP, SEXP n_foldSEXP, SEXP custom_thetaSEXP, SEXP n_threadsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::VectorXd> >::type y(ySEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXd> >::type masterZ(masterZSEXP);
    Rcpp::traits::input_parameter< const Eigen::Map<Eigen::MatrixXi> >::type MAP(MAPSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< Eigen::ArrayXXd >::type theta(thetaSEXP);
    Rcpp::traits::input_parameter< int >::type max_itr(max_itrSEXP);
    Rcpp::traits::input_parameter< double >::type convergence_cutoff(convergence_cutoffSEXP);
    Rcpp::traits::input_parameter< bool >::type REML(REMLSEXP);
    Rcpp::traits::input_parameter< bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< bool >::type timings(timingsSEXP);
    Rcpp::traits::input_parameter< int >::type n_fold(n_foldSEXP);
    Rcpp::traits::input_parameter< bool >::type custom_theta(custom_thetaSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_DEbeta(X, y, masterZ, MAP, n, k, t, theta, max_itr, convergence_cutoff, REML, verbose, timings, n_fold, custom_theta, n_threads, seed));
    return rcpp_result_gen;
END_RCPP
}
// covCalc
Eigen::MatrixXd covCalc(const Eigen::MatrixXd& X, const Eigen::MatrixXi& MAP);
RcppExport SEXP _DCENt_covCalc(SEXP XSEXP, SEXP MAPSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type MAP(MAPSEXP);
    rcpp_result_gen = Rcpp::wrap(covCalc(X, MAP));
    return rcpp_result_gen;
END_RCPP
}
// Z_assemble
Eigen::MatrixXd Z_assemble(const Eigen::MatrixXd& masterZ, const Eigen::MatrixXi& MAP, int i, int k, int t, int kt);
RcppExport SEXP _DCENt_Z_assemble(SEXP masterZSEXP, SEXP MAPSEXP, SEXP iSEXP, SEXP kSEXP, SEXP tSEXP, SEXP ktSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type masterZ(masterZSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type MAP(MAPSEXP);
    Rcpp::traits::input_parameter< int >::type i(iSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type kt(ktSEXP);
    rcpp_result_gen = Rcpp::wrap(Z_assemble(masterZ, MAP, i, k, t, kt));
    return rcpp_result_gen;
END_RCPP
}
// calc_ZDZ_plus_E_list
Rcpp::List calc_ZDZ_plus_E_list(const Eigen::MatrixXd& masterZt, const Eigen::MatrixXd& D, const Eigen::VectorXd& E, const Eigen::MatrixXi& MAP, int n, int k, int t);
RcppExport SEXP _DCENt_calc_ZDZ_plus_E_list(SEXP masterZtSEXP, SEXP DSEXP, SEXP ESEXP, SEXP MAPSEXP, SEXP nSEXP, SEXP kSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type masterZt(masterZtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type E(ESEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type MAP(MAPSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_ZDZ_plus_E_list(masterZt, D, E, MAP, n, k, t));
    return rcpp_result_gen;
END_RCPP
}
// calc_ZDZ_plus_E
Rcpp::List calc_ZDZ_plus_E(const Eigen::MatrixXd& masterZt, const Eigen::MatrixXd& D, const Eigen::VectorXd& E, const Eigen::MatrixXi& MAP, int n, int k, int t, int nkt);
RcppExport SEXP _DCENt_calc_ZDZ_plus_E(SEXP masterZtSEXP, SEXP DSEXP, SEXP ESEXP, SEXP MAPSEXP, SEXP nSEXP, SEXP kSEXP, SEXP tSEXP, SEXP nktSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type masterZt(masterZtSEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXd& >::type D(DSEXP);
    Rcpp::traits::input_parameter< const Eigen::VectorXd& >::type E(ESEXP);
    Rcpp::traits::input_parameter< const Eigen::MatrixXi& >::type MAP(MAPSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    Rcpp::traits::input_parameter< int >::type nkt(nktSEXP);
    rcpp_result_gen = Rcpp::wrap(calc_ZDZ_plus_E(masterZt, D, E, MAP, n, k, t, nkt));
    return rcpp_result_gen;
END_RCPP
}
// check_openmp
bool check_openmp();
RcppExport SEXP _DCENt_check_openmp() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(check_openmp());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_DCENt_estimate_D", (DL_FUNC) &_DCENt_estimate_D, 8},
    {"_DCENt_estimate_E", (DL_FUNC) &_DCENt_estimate_E, 8},
    {"_DCENt_estimate_all", (DL_FUNC) &_DCENt_estimate_all, 14},
    {"_DCENt_estimate_DEbeta", (DL_FUNC) &_DCENt_estimate_DEbeta, 17},
    {"_DCENt_covCalc", (DL_FUNC) &_DCENt_covCalc, 2},
    {"_DCENt_Z_assemble", (DL_FUNC) &_DCENt_Z_assemble, 6},
    {"_DCENt_calc_ZDZ_plus_E_list", (DL_FUNC) &_DCENt_calc_ZDZ_plus_E_list, 7},
    {"_DCENt_calc_ZDZ_plus_E", (DL_FUNC) &_DCENt_calc_ZDZ_plus_E, 8},
    {"_DCENt_check_openmp", (DL_FUNC) &_DCENt_check_openmp, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_DCENt(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
