# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_V <- function(X, y, V, beta, MAP, n, k, t) {
    .Call('_PLoCONE_estimate_V', PACKAGE = 'PLoCONE', X, y, V, beta, MAP, n, k, t)
}

estimate_D <- function(r0, Z, D, E, V, MAP, n, k, t) {
    .Call('_PLoCONE_estimate_D', PACKAGE = 'PLoCONE', r0, Z, D, E, V, MAP, n, k, t)
}

estimate_E <- function(r0, Z, D, E, V, MAP, n, k, t) {
    .Call('_PLoCONE_estimate_E', PACKAGE = 'PLoCONE', r0, Z, D, E, V, MAP, n, k, t)
}

thresholdRange <- function(R, theta, cov, MAP, lower, upper) {
    invisible(.Call('_PLoCONE_thresholdRange', PACKAGE = 'PLoCONE', R, theta, cov, MAP, lower, upper))
}

threshold <- function(abscov, signcov, thetalambda, sigma_out) {
    invisible(.Call('_PLoCONE_threshold', PACKAGE = 'PLoCONE', abscov, signcov, thetalambda, sigma_out))
}

threshold_V <- function(R, sigma, theta, MAP, n_fold = 5L) {
    .Call('_PLoCONE_threshold_V', PACKAGE = 'PLoCONE', R, sigma, theta, MAP, n_fold)
}

calc_ZDZ_wrapper <- function(Z, D, E, MAP, n, k, t) {
    .Call('_PLoCONE_calc_ZDZ_wrapper', PACKAGE = 'PLoCONE', Z, D, E, MAP, n, k, t)
}

threshold_D <- function(D, nonzero_pct) {
    .Call('_PLoCONE_threshold_D', PACKAGE = 'PLoCONE', D, nonzero_pct)
}

initial_estimates <- function(X, y, MAP, n, k, t) {
    .Call('_PLoCONE_initial_estimates', PACKAGE = 'PLoCONE', X, y, MAP, n, k, t)
}

estimate_all <- function(X, y, Z_in, n, k, t, max_itr = 250L, covtype = "", idx = 0L, REML = FALSE, eigen_threshold = 0.001) {
    .Call('_PLoCONE_estimate_all', PACKAGE = 'PLoCONE', X, y, Z_in, n, k, t, max_itr, covtype, idx, REML, eigen_threshold)
}

estimate_DEbeta <- function(X, y, Z_in, n, k, t, max_itr = 250L, covtype = "", REML = FALSE, eigen_threshold = 0.001) {
    .Call('_PLoCONE_estimate_DEbeta', PACKAGE = 'PLoCONE', X, y, Z_in, n, k, t, max_itr, covtype, REML, eigen_threshold)
}

covCalc <- function(X, MAP, print = FALSE) {
    .Call('_PLoCONE_covCalc', PACKAGE = 'PLoCONE', X, MAP, print)
}

