# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_all <- function(X, y, Z_in, n, k, t, max_itr = 250L, covtype = "", idx = 0L, REML = FALSE, eigen_threshold = 0.001) {
    .Call('_PLoCONE_estimate_all', PACKAGE = 'PLoCONE', X, y, Z_in, n, k, t, max_itr, covtype, idx, REML, eigen_threshold)
}

estimate_DEbeta <- function(X, y, Z_in, n, k, t, max_itr = 250L, covtype = "", REML = FALSE, eigen_threshold = 0.001) {
    .Call('_PLoCONE_estimate_DEbeta', PACKAGE = 'PLoCONE', X, y, Z_in, n, k, t, max_itr, covtype, REML, eigen_threshold)
}

covCalc <- function(X, MAP, print) {
    .Call('_PLoCONE_covCalc', PACKAGE = 'PLoCONE', X, MAP, print)
}

calc_ZDZ_plus_E_list <- function(Z, D, E, n, k, t) {
    .Call('_PLoCONE_calc_ZDZ_plus_E_list', PACKAGE = 'PLoCONE', Z, D, E, n, k, t)
}

