# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

estimate_all <- function(X, y, Z_in, n, k, t, max_itr = 250L, convergence_cutoff = 0.00005, REML = FALSE) {
    .Call('_DINE_estimate_all', PACKAGE = 'DINE', X, y, Z_in, n, k, t, max_itr, convergence_cutoff, REML)
}

estimate_DEbeta <- function(X, y, Z_in, n, k, t, max_itr = 250L, convergence_cutoff = 0.0001, REML = FALSE, verbose = FALSE, n_fold = 5L, seed = 1234L) {
    .Call('_DINE_estimate_DEbeta', PACKAGE = 'DINE', X, y, Z_in, n, k, t, max_itr, convergence_cutoff, REML, verbose, n_fold, seed)
}

covCalc <- function(X, MAP, print) {
    .Call('_DINE_covCalc', PACKAGE = 'DINE', X, MAP, print)
}

calc_ZDZ_plus_E_list <- function(Z, D, E, n, k, t) {
    .Call('_DINE_calc_ZDZ_plus_E_list', PACKAGE = 'DINE', Z, D, E, n, k, t)
}

